const scheduleDataDay2 = [
	{
		id: 0,
		title: "Operheimer Slot-II",
		time: "09:00 AM",
		location: "QEDM, Department of Industrial and Systems Engineering",
		link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
		image: "assets/schedule/Operheimer.png",
		position: "left",
	},
	{
		id: 1,
		title: "Stratathon Slot-II",
		time: "09:00 AM",
		location: "NR-312, Nalanda Classroom Complex",
		link: "https://maps.app.goo.gl/4E9RiAob3fenRGjj9",
		image: "assets/schedule/Stratathon.png",
		position: "right",
	},
	{
		id: 2,
		title: "HachTank Presentations",
		time: "09:30 AM",
		location: "Seminar Room, Dept. of Industrial and Systems Engg.",
		link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
		image: "assets/schedule/HackTank.png",
		position: "left",
	},
	{
		id: 3,
		title: "AI Odessey Event & LiveAI Workshop",
		time: "10:30 AM",
		location: "Raman Auditorium",
		link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
		image: "assets/schedule/LiveAI.png",
		position: "right",
	},
	// {
	// 	id: 4,
	// 	title: " blue yonder Round-II",
	// 	time: "11:00 AM",
	// 	location: "E1, Department of Industrial & Systems Engg.",
	// 	link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
	// 	image: "assets/schedule/Datavantage.png",
	// 	position: "left",
	// },
	{
		id: 5,
		title: "Datavantage Round-II",
		time: "11:30 AM",
		location: "E1, Department of Industrial & Systems Engg.",
		link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
		image: "assets/schedule/Datavantage.png",
		position: "left",
	},
	{
		id: 5,
		title: "Strategy Sutram",
		time: "02:00 PM",
		location: "QEDM, Department of Industrial and Systems Engineering",
		link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
		image: "assets/schedule/Strategy_Sutram.png",
		position: "right",
	},
	{
		id: 6,
		title: "Dr. Tanushyam Chattopadhyay, Guest Lecture", //no such guest
		time: "02:00 PM",
		location: "Raman Auditorium",
		link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
		image: "assets/schedule/Tanushyam_Chattopadhyay.png",
		position: "left",
	},
	{
		id: 7,
		title: "INDIA v/s NEW ZEALAND Live Screening",
		time: "02:00 PM",
		location: "TOAT (Tagore Open Air Theatre)",
		link: "https://maps.app.goo.gl/HmSw3iNir6ewdKRz9",
		image: "assets/schedule/INDvsNZ.png",
		position: "right",
	},
	{
		id: 8,
		title: "Dr. Arvind Kumar, Guest Lecture",
		time: "03:00 PM",
		location: "Raman Auditorium",
		link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
		image: "assets/schedule/ArvindKumar.png",
		position: "left",
	},
	{
		id: 9,
		title: "Closing Ceremony",
		time: "04:00 PM",
		location: "Seminar Room, Dept. of Industrial and Systems Engg.",
		link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
		image: null,
		position: "right",
	},
	// {
	//   id: 9,
	//   title: "Operheimer, Slot-I",
	//   time: "05:30 PM",
	//   location: "Seminar Room, Dept. of Industrial and Systems Engg.",
	//   link: "https://maps.app.goo.gl/WiBZ3Af6SkEHMK2p9",
	//   image: null,
	//   position: "right",
	// },
	// {
	//   id: 10,
	//   title: "Tech-Powered Growth-Innovations Driving Business Success, Workshop",
	//   time: "06:00 PM",
	//   location: "Raman Auditorium",
	//   link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
	//   image: null,
	//   position: "left",
	// },
	// {
	//   id: 12,
	//   title: "Women's Panel",
	//   time: "08:00 PM",
	//   location: "Raman Auditorium",
	//   link: "https://maps.app.goo.gl/kvrZb65Pt98DjLN8A",
	//   image: null,
	//   position: "right",
	// },
];

export default scheduleDataDay2;
