name: Deploy to Netlify

on:
  push:
    branches:
      - master # Replace with your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

    

          # Step 3: Build the project with VITE_API_BACKEND_URL
      - name: Build project
        env:
          VITE_API_BASE_URL: "https://optima-2025-backend-bfa8ccdhefdgb4bs.centralindia-01.azurewebsites.net"
        run: npm run build

      # Step 4: Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=dist --site=$NETLIFY_SITE_ID --prod
