name: Deploy to Netlify

on:
    push:
        branches:
            - master # Replace with your default branch name
    pull_request:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Check out the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Install dependencies
            - name: Install dependencies
              run: npm install

            # Step 3: Build the project
            - name: Build project
              run: npm run build

            # Step 4: Deploy to Netlify
            - name: Deploy to Netlify
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              run: |
                  npm install -g netlify-cli
                  netlify deploy --dir=build --site=$NETLIFY_SITE_ID --prod
